repos:
# YAML
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

# Markdown
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.36.0
  hooks:
    - id: markdownlint
      args: ["--fix"]

# GitHub Actions
- repo: https://github.com/bridgecrewio/checkov.git
  rev: 2.4.14
  hooks:
    - id: checkov
      files: .+
      verbose: false
