repos:
# YAML
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

# Markdown
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.43.0
  hooks:
    - id: markdownlint
      args: ["--fix"]

# GitHub Actions
- repo: https://github.com/bridgecrewio/checkov.git
  rev: 3.2.346
  hooks:
    - id: checkov
      files: .+
      verbose: false
